// console.log("hello");

// let str1="hello i am sakshi";
// let str2='hello i am sakshi';

// console.log(str1==str2)


// let str3





// let str1= new String('good morning sakshi')   
//             //call a constructor when making new object

// console.log(str1)

// console.log(typeof str1) 



// let 


// console.log("berry" < " Berry"); 



//length is given preference when its uneven 
//when length is same unicodes are compared
//string literal are called dynamic string
//STrigns are immutable

// let str1=`you ar learning string today
//  and we are enrolled in mern stack!`
// console.log(str1)

// let student1="sakshi";
// let student2="shivtej";

// let list=`list of my students include ${student1} and ${student2}`;
// console.log(list)




// let currentYear=2025;
// let birthyear=2003;
// let myIntro=`my name is sakshi and i will have ${currentYear-birthyear>20?"wine":"milk"}`
// console.log(myIntro)

// //diff between method and function

// //Don't call fucntions in template literals.

// let YourName=prompt("enter your name");
// console.log(YourName.toUpperCase());
// console.log(YourName.toLowerCase());


// let sentence=" i am an Avenger called Ironman"
// // console.log(sentence.includes("Avenger"))


// // console.log(sentence.indexOf("a"))
// // console.log(sentence.indexOf("called"))

// console.log(sentence.indexOf("p"))

// console.log(sentence.slice(3,16));
// console.log(sentence.substring(16,3))


//hold
// let Name="Bantu"
// "utnaB"


// // start=0;
// // end=Name.length-1
// let j=Name.length-1
// let i=0
// let reverse_name="";

// while(i<=j){
    
//     reverse_string+=Name[i]=Name[j] + Name[j]= Name[i];
   
//     i++;
//     j--;

// }




// let str2="aabbbccc";
// for(let i =0; i<str2.length;i++){

// }

             
//passward strength calculator: string validator.
//randome passward generator













